spring.application.name=EcoSim
spring.datasource.url=jdbc:postgresql://localhost:5432/dBecosim
spring.datasource.username=postgres
spring.datasource.password=mohamed@1230

spring.jpa.hibernate.ddl-auto=update



spring.ai.ollama.base-url=http://host.docker.internal:11434

spring.ai.ollama.chat.options.model=gemma3:4b


spring.ai.ollama.chat.options.format=json

ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjE3OGNjMWRiN2QxYzQzYzc5YzUxMzAzZTc1NGZiNWY0IiwiaCI6Im11cm11cjY0In0=
ors.api.url=https://api.openrouteservice.org/v2/directions/driving-car

